-- PostgreSQL 16 + PostGIS, UTC at storage boundary; monetary amounts as integer JPY.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE app_users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), display_name text NOT NULL, phone_ciphertext bytea NOT NULL, verification_status text NOT NULL CHECK(verification_status IN ('pending','verified','rejected')), created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE organizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), legal_name text NOT NULL, address text NOT NULL, contact text NOT NULL, review_status text NOT NULL CHECK(review_status IN ('pending','approved','rejected')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_members(org_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES app_users(id), role text NOT NULL CHECK(role IN ('owner','manager','reviewer')), PRIMARY KEY(org_id,user_id));
CREATE TABLE worker_skills(worker_id uuid NOT NULL REFERENCES app_users(id), skill_code text NOT NULL, valid_until date, verified_at timestamptz, PRIMARY KEY(worker_id,skill_code));
CREATE TABLE jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES organizations(id), title text NOT NULL, category text NOT NULL, contract_type text NOT NULL CHECK(contract_type IN ('employment','contractor')), status text NOT NULL CHECK(status IN ('draft','pending_review','published','filled','expired','cancelled')), description text NOT NULL, address_ciphertext bytea NOT NULL, public_point geography(Point,4326), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, amount_yen bigint NOT NULL CHECK(amount_yen>0), capacity integer NOT NULL CHECK(capacity>0), reserved_count integer NOT NULL DEFAULT 0 CHECK(reserved_count>=0), cancellation_policy text NOT NULL, required_skills text[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_at>starts_at), CHECK(reserved_count<=capacity));
CREATE INDEX jobs_public_geo ON jobs USING gist(public_point) WHERE status='published';
CREATE INDEX jobs_public_time ON jobs(starts_at) WHERE status='published';
CREATE TABLE assignments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES jobs(id), worker_id uuid NOT NULL REFERENCES app_users(id), state text NOT NULL CHECK(state IN ('accepted','traveling','checked_in','working','submitted','approved','payable','paid','cancelled','disputed','needs_revision')), accepted_amount_yen bigint NOT NULL CHECK(accepted_amount_yen>0), accepted_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE UNIQUE INDEX one_active_assignment_per_worker_job ON assignments(job_id,worker_id) WHERE state NOT IN ('cancelled');
CREATE TABLE delivery_stops(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), worker_id uuid NOT NULL REFERENCES app_users(id), scheduled_date date NOT NULL, address_ciphertext bytea NOT NULL, location geography(Point,4326), time_start timestamptz, time_end timestamptz, status text NOT NULL CHECK(status IN ('draft','ready','en_route','arrived','delivered','failed','deferred')), note_ciphertext bytea, created_at timestamptz NOT NULL DEFAULT now(), CHECK(time_end IS NULL OR time_start IS NULL OR time_end>time_start));
CREATE INDEX delivery_stops_worker_date ON delivery_stops(worker_id,scheduled_date);
CREATE TABLE evidence(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid REFERENCES assignments(id), delivery_stop_id uuid REFERENCES delivery_stops(id), object_key text NOT NULL UNIQUE, sha256 text NOT NULL, mime_type text NOT NULL, uploaded_by uuid NOT NULL REFERENCES app_users(id), created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, CHECK((assignment_id IS NOT NULL)::int+(delivery_stop_id IS NOT NULL)::int=1));
CREATE TABLE idempotency_keys(actor_id uuid NOT NULL REFERENCES app_users(id), key text NOT NULL, request_hash text NOT NULL, status_code integer NOT NULL, response_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(actor_id,key));
CREATE TABLE domain_events(id bigserial PRIMARY KEY, entity_type text NOT NULL, entity_id uuid NOT NULL, event_type text NOT NULL, actor_id uuid REFERENCES app_users(id), payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX domain_events_entity ON domain_events(entity_type,entity_id,created_at);
CREATE TABLE outbox(id bigserial PRIMARY KEY, event_id bigint NOT NULL UNIQUE REFERENCES domain_events(id), topic text NOT NULL, payload jsonb NOT NULL, delivered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES assignments(id), entry_type text NOT NULL CHECK(entry_type IN ('earned','reversal','paid','refund')), amount_yen bigint NOT NULL, provider_reference text UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE provider_webhooks(provider text NOT NULL, external_event_id text NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(provider,external_event_id));
-- Every accept must run in a DB transaction: lock jobs row, validate status/capacity/worker eligibility, increment reserved_count, insert assignment + domain event + outbox, commit.
