'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { postAuth } from '@happydrive/web-ui/client/api';
import { AppShell, Alert, LoadingState } from '@happydrive/web-ui/components';
import { COOKIE_PREFIX } from '@/lib/config';
import { marketplaceFetch as api,requestStatuses,nextStatuses,type MarketplaceAccount,type Service,type RequestSummary,type RequestDetail } from '@/lib/marketplace';
import './style.css';

type View='overview'|'catalog'|'requests'|'plans'|'services'|'feed';
const date=(s:string)=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
export default function MarketplacePage(){
  const [account,setAccount]=useState<MarketplaceAccount|null>(null);const [catalog,setCatalog]=useState<Service[]>([]);const [requests,setRequests]=useState<RequestSummary[]>([]);
  const [view,setView]=useState<View>('overview');const [mode,setMode]=useState<'customer'|'supplier'>('customer');const [supplierId,setSupplierId]=useState('');
  const [services,setServices]=useState<Service[]>([]);const [feed,setFeed]=useState<RequestSummary[]>([]);const [selected,setSelected]=useState<RequestDetail|null>(null);
  const [compose,setCompose]=useState<Service|null>(null);const [error,setError]=useState('');const [pending,setPending]=useState(false);const [loading,setLoading]=useState(true);
  const [staff,setStaff]=useState<{id:string;familyName:string;givenName:string}[]>([]);
  const [messages,setMessages]=useState<{id:string;body:string;createdAt:string}[]>([]);
  const keys=useRef(new Map<string,string>());
  async function reload(){
    const [a,c,r]=await Promise.all([api<MarketplaceAccount>('/me'),api<{items:Service[]}>('/catalog'),api<{items:RequestSummary[]}>('/requests')]);
    setAccount(a);setCatalog(c.items);setRequests(r.items);
    if(a.suppliers.length && !supplierId)setSupplierId(a.suppliers[0]!.id);
  }
  useEffect(()=>{const change=()=>{const value=window.location.hash.slice(1);if(['overview','catalog','requests','plans','services','feed'].includes(value)){setView(value as View);setSelected(null);setCompose(null);}};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  useEffect(()=>{let alive=true;Promise.all([api<MarketplaceAccount>('/me'),api<{items:Service[]}>('/catalog'),api<{items:RequestSummary[]}>('/requests')]).then(([a,c,r])=>{if(alive){setAccount(a);setCatalog(c.items);setRequests(r.items);setSupplierId(a.suppliers[0]?.id??'');}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
  useEffect(()=>{let alive=true;if(!supplierId)return;Promise.all([api<{items:Service[]}>(`/suppliers/${supplierId}/services`),api<{items:RequestSummary[]}>(`/suppliers/${supplierId}/feed`),api<{items:typeof staff}>(`/suppliers/${supplierId}/members`)]).then(([s,f,m])=>{if(alive){setServices(s.items);setFeed(f.items);setStaff(m.items);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[supplierId,requests]);
  async function act(path:string,body?:unknown,method='POST'){
    if(pending)return;setPending(true);setError('');const scope=JSON.stringify({path,body,method});let key=keys.current.get(scope);if(!key){key=crypto.randomUUID();keys.current.set(scope,key);}
    try{await api(path,method,body,key);keys.current.delete(scope);await reload();if(selected)setSelected(await api<RequestDetail>(`/requests/${selected.id}`));return true;}
    catch(e){setError(e instanceof Error?e.message:'通信を確認して再試行してください');return false;}finally{setPending(false);}
  }
  async function open(id:string){setError('');try{const r=await api<RequestDetail>(`/requests/${id}`);setSelected(r);setMessages((await api<{items:typeof messages}>(`/requests/${id}/messages`)).items);}catch(e){setError(e instanceof Error?e.message:'読み込めませんでした');}}
  function form(e:React.FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));}
  const nav=((mode==='customer'?[['overview','ホーム'],['catalog','サービス'],['requests','依頼履歴'],['plans','会員プラン']]:[['overview','概要'],['feed','募集中の依頼'],['requests','受諾・実施'],['services','サービス'],['plans','料金・契約']]) as [string,string][]).map(([id,label])=>({href:'#'+id,label}));
  return <AppShell brandSub={mode==='customer'?'暮らしの支援':'供給者ポータル'} nav={nav} sidebarFooter={<><Link href="/dashboard">配送・企業ポータル</Link><button className="mp-button" onClick={async()=>{await postAuth(COOKIE_PREFIX,'/api/auth/logout',{});// eslint-disable-next-line @next/next/no-location-assign-relative-destination
window.location.assign('/customer-login');}}>ログアウト</button></>}>
    <div onClick={e=>{const a=(e.target as HTMLElement).closest('a[href^="#"]');if(a){e.preventDefault();setSelected(null);setCompose(null);setView(a.getAttribute('href')!.slice(1) as View);}}} className="mp-mobile-nav">{nav.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</div>
    <header className="mp-header"><div><p className="hd-muted">HappyDrive</p><h1>{mode==='customer'?'毎日の暮らしに、頼れる支援を。':'供給者ダッシュボード'}</h1><p>依頼・サービス・契約を一か所で管理</p></div><label>利用モード<select className="hd-select" value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setView('overview');setSelected(null);}}><option value="customer">顧客</option><option value="supplier">供給者</option></select></label></header>
    {mode==='supplier' && account?.suppliers.length!==0 && <label>供給者<select className="hd-select" value={supplierId} onChange={e=>setSupplierId(e.target.value)}>{account?.suppliers.map(s=><option key={s.id} value={s.id}>{s.legalName}</option>)}</select></label>}
    {error && <Alert title="操作を完了できませんでした" tone="red">{error}<button className="mp-button" onClick={()=>{setLoading(true);reload().catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>再読み込み</button></Alert>}
    {loading?<LoadingState />:!account?null:<>
      {!account.profile && <section className="mp-card"><h2>顧客の登録</h2><p>電話番号を確認して、プロフィールを登録してください。</p><form className="mp-grid" onSubmit={e=>{const b=form(e);void act('/customer',b,'PUT');}}><label>姓<input className="hd-input" name="familyName" required maxLength={60}/></label><label>名<input className="hd-input" name="givenName" required maxLength={60}/></label><label>住所<input className="hd-input" name="address" required maxLength={500}/></label><button className="mp-button" disabled={pending}>登録する</button></form><Link href="/customer-login">電話番号でログイン</Link></section>}
      {mode==='supplier' && !supplierId && <section className="mp-card"><h2>供給者アカウントがありません</h2><p>事業者の確認・参加手続き後にサービスと依頼を管理できます。</p>{account.profile && <form className="hd-stack" onSubmit={e=>{const b=form(e);void act('/suppliers',b);}}><label>事業者名<input className="hd-input" name="legalName" required maxLength={120}/></label><label>事業区分<select className="hd-select" name="supplierType"><option value="company">法人</option><option value="sole_proprietor">個人事業主</option></select></label><label>所在地<input className="hd-input" name="address" required maxLength={500}/></label><button className="mp-button" disabled={pending}>登録を申請</button></form>}</section>}
      {view==='overview' && !selected && !compose && <><div className="mp-grid"><section className="mp-card"><p>進行中の依頼</p><strong className="mp-number">{requests.filter(r=>!['completed','cancelled','disputed'].includes(r.status??'')).length}<small>件</small></strong></section><section className="mp-card"><p>{mode==='customer'?'利用可能なサービス':'登録サービス'}</p><strong className="mp-number">{mode==='customer'?catalog.length:services.length}<small>件</small></strong></section><section className="mp-card"><p>会員プラン</p><strong>{account.subscription?.planCode??'未契約'}</strong>{account.subscription?.trialEndsAt && <p>無料期間終了 {date(account.subscription.trialEndsAt)}</p>}</section></div><section className="mp-card"><h2>{mode==='customer'?'どんな支援が必要ですか？':'案件を確認する'}</h2><p>買い物、訪問、配送など、暮らしを支えるサービス。</p><button className="mp-button" onClick={()=>setView(mode==='customer'?'catalog':'feed')}>{mode==='customer'?'サービスを見る':'募集中の依頼を見る'}</button></section></>}
      {view==='plans' && <><div className="mp-grid">{[{name:'ベーシック',price:1900,quota:'月5件'},{name:'スタンダード',price:4900,quota:'月12件'},{name:'ケア',price:9900,quota:'月間上限なし・1日2件'}].map(p=><section className="mp-card" key={p.name}><h2>{p.name}</h2><strong className="mp-number">¥{p.price.toLocaleString()}<small>/月</small></strong><p>{p.quota}</p><p>初回30日無料</p></section>)}</div><section className="mp-card"><h2>お申込み受付準備中</h2><p>個別サービス料金・契約条件の確定後にお申込みいただけます。供給者の初回無料期間は7日間です。</p></section></>}
      {view==='catalog' && !compose && <div className="mp-grid">{catalog.length===0?<section className="mp-card"><h2>サービスの準備中です</h2><p>審査・公開されたサービスがここに表示されます。</p></section>:catalog.map(s=><section className="mp-card" key={s.id}><p className="hd-muted">{s.supplierName}</p><h2>{s.name}</h2><p>{s.description}</p><p>{s.durationMinutes}分 · {s.pricePolicy}</p><button className="mp-button" onClick={()=>setCompose(s)}>依頼内容を入力</button></section>)}</div>}
      {compose && <section className="mp-card"><h2>{compose.name}の依頼</h2><p>投稿時に依頼枠を予約します。未受諾のキャンセルで返却し、完了確認後に消費します。</p><form className="hd-stack" onSubmit={async e=>{const b=form(e);if(await act('/requests',{...b,serviceId:compose.id,startsAt:new Date(String(b.startsAt)+'+09:00').toISOString(),endsAt:new Date(String(b.endsAt)+'+09:00').toISOString()})){setCompose(null);setView('requests');}}}><label>タイトル<input className="hd-input" name="title" required maxLength={120}/></label><label>内容<textarea className="hd-input" name="details" required maxLength={3000}/></label><label>現場住所<input className="hd-input" name="address" required maxLength={500}/></label><label>地域<select className="hd-select" name="areaCode">{compose.areaCodes.map(a=><option key={a}>{a}</option>)}</select></label><div className="mp-grid"><label>開始（日本時間）<input className="hd-input" name="startsAt" type="datetime-local" required/></label><label>終了（日本時間）<input className="hd-input" name="endsAt" type="datetime-local" required/></label></div><p>サービス料金は受付開始前に確定・表示されます。</p><button className="mp-button" disabled={pending || !account.subscription}>依頼を投稿</button><button type="button" className="mp-button" onClick={()=>setCompose(null)}>戻る</button>{!account.subscription && <p>依頼には有効な会員プランが必要です。</p>}</form></section>}
      {view==='feed' && <section className="mp-card"><h2>募集中の依頼</h2>{feed.length===0?<p>対応可能な依頼はありません。</p>:feed.map(r=><article className="mp-request" key={r.id}><h3>{r.title}</h3><p>{r.areaCode} · {date(r.startsAt)}</p><p>受諾前は詳細住所を表示しません。</p><form onSubmit={e=>{const b=form(e);void act(`/requests/${r.id}/accept`,{supplierId,staffId:b.staffId});}}><label>担当者<select className="hd-select" name="staffId" required>{staff.map(m=><option key={m.id} value={m.id}>{m.familyName} {m.givenName}</option>)}</select></label><button className="mp-button" disabled={pending}>条件を確認して受諾</button></form></article>)}</section>}
      {view==='requests' && !selected && <section className="mp-card"><h2>依頼履歴</h2>{requests.length===0?<p>依頼はまだありません。</p>:requests.map(r=><button className="mp-request" key={r.id} onClick={()=>void open(r.id)}><strong>{r.title}</strong><span>{requestStatuses[r.status??'']??r.status}</span><span>{date(r.startsAt)}</span></button>)}</section>}
      {selected && <section className="mp-card"><button className="mp-button" onClick={()=>setSelected(null)}>履歴に戻る</button><h2>{selected.title}</h2><p>{requestStatuses[selected.status]}</p><p>{selected.address}</p><p>{selected.details}</p><p>{date(selected.startsAt)} · {selected.supplierName}</p>{mode==='supplier' && nextStatuses[selected.status] && <button className="mp-button" disabled={pending} onClick={()=>void act(`/requests/${selected.id}/status`,{status:nextStatuses[selected.status]})}>{requestStatuses[nextStatuses[selected.status]!]}に進む</button>}{mode==='customer' && selected.status==='awaiting_customer_confirmation' && <p>内容を確認して、iPhoneアプリで完了QRを表示してください。</p>}{mode==='customer' && selected.status==='open' && <button className="mp-button" disabled={pending} onClick={()=>{const reason=window.prompt('キャンセル理由');if(reason)void act(`/requests/${selected.id}/cancel`,{reason});}}>キャンセル</button>}{['accepted','en_route','arrived','in_progress','awaiting_customer_confirmation'].includes(selected.status) && <button className="mp-button" disabled={pending} onClick={()=>{const reason=window.prompt('サポートへの相談内容');if(reason)void act(`/requests/${selected.id}/dispute`,{reason});}}>サポートに相談</button>}<h3>メッセージ</h3>{messages.map(m=><p key={m.id}>{m.body}<small> · {date(m.createdAt)}</small></p>)}<form onSubmit={async e=>{const target=e.currentTarget;const b=form(e);if(await act(`/requests/${selected.id}/messages`,b)){target.reset();setMessages((await api<{items:typeof messages}>(`/requests/${selected.id}/messages`)).items);}}}><label>メッセージ<textarea className="hd-input" name="body" required maxLength={3000}/></label><button className="mp-button" disabled={pending}>送信</button></form></section>}
      {view==='services' && supplierId && <><section className="mp-card"><h2>対応できる時間帯</h2><form className="hd-stack" onSubmit={async e=>{const target=e.currentTarget;const b=form(e);if(await act(`/suppliers/${supplierId}/availability`,{...b,startsAt:new Date(String(b.startsAt)+'+09:00').toISOString(),endsAt:new Date(String(b.endsAt)+'+09:00').toISOString()}))target.reset();}}><label>担当者<select className="hd-select" name="staffId">{staff.map(m=><option key={m.id} value={m.id}>{m.familyName} {m.givenName}</option>)}</select></label><label>開始（日本時間）<input className="hd-input" name="startsAt" type="datetime-local" required/></label><label>終了（日本時間）<input className="hd-input" name="endsAt" type="datetime-local" required/></label><button className="mp-button" disabled={pending}>登録する</button></form></section><section className="mp-card"><h2>登録サービス</h2>{services.map(s=><article className="mp-request" key={s.id}><h3>{s.name}</h3><p>{s.description}</p><p>{s.status==='published'?'公開中':s.status==='pending_review'?'審査中':'非公開'}</p></article>)}</section><section className="mp-card"><h2>サービスを登録</h2><form className="hd-stack" onSubmit={async e=>{const target=e.currentTarget;const b=form(e);if(await act(`/suppliers/${supplierId}/services`,{...b,areaCodes:String(b.areaCodes).split(',').map(x=>x.trim()),durationMinutes:Number(b.durationMinutes)}))target.reset();}}><label>名称<input className="hd-input" name="name" required maxLength={120}/></label><label>カテゴリ<select className="hd-select" name="category"><option value="shopping_assist">買い物支援</option><option value="delivery">配送</option><option value="companionship">訪問・見守り</option><option value="household_help">家事支援</option></select></label><label>説明<textarea className="hd-input" name="description" required maxLength={3000}/></label><label>対象地域コード（カンマ区切り）<input className="hd-input" name="areaCodes" required/></label><label>所要時間（分）<input className="hd-input" name="durationMinutes" type="number" min={1} max={1440} required/></label><label>価格・見積方法<input className="hd-input" name="pricePolicy" required maxLength={500}/></label><button className="mp-button" disabled={pending}>審査を申請</button></form></section></>}
    </>}
  </AppShell>;
}
