'use client';
import {useEffect,useState} from 'react';
import {CSRF_HEADER,readCsrfToken} from '@happydrive/web-ui/client/api';
import {useAdmin} from '@/lib/admin-context';
import {COOKIE_PREFIX} from '@/lib/config';
type Supplier={id:string;legalName:string;reviewStatus:string};type Service={id:string;name:string;supplierName:string;status:string;description:string;pricePolicy:string};type Dispute={id:string;title:string;reviewId:string|null;proposedBy:string|null;proposedDecision:string|null;reason:string|null;evidenceSummary:string|null};
type SupplierDetails={id:string;legalName:string;address:string;application:Record<string,string|string[]>|null;evidenceIds:string[]};
type DisputeDetails={id:string;title:string;details:string;address:string;messages:{body:string;createdAt:string}[]};
const statuses:Record<string,string>={pending:'審査待ち',approved:'承認済み',rejected:'差戻し',invited_unverified:'招待候補・未確認',pending_review:'サービス審査待ち',paused:'休止中',resolved_completed:'完了として解決',resolved_cancelled:'取消・枠返却として解決'};
const fieldLabels:Record<string,string>={businessCategory:'事業分類',registrationNumber:'登録番号',areaCodes:'作業エリア',openingHours:'営業時間',insuranceSummary:'保険・安全管理',contactEmail:'連絡先メール',description:'事業内容'};
async function request<T>(path:string,method='GET',body?:unknown):Promise<T>{const res=await fetch('/api/hd'+path,{method,cache:'no-store',headers:method==='GET'?{}:{'content-type':'application/json',[CSRF_HEADER]:readCsrfToken(COOKIE_PREFIX)??'','idempotency-key':crypto.randomUUID()},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await res.json();if(!res.ok)throw new Error(data.message??'接続できませんでした');return data as T;}
export default function MarketplaceAdmin(){
 const {me,isOperator}=useAdmin();const [data,setData]=useState<{suppliers:Supplier[];services:Service[];disputes:Dispute[]}|null>(null);const [supplier,setSupplier]=useState<SupplierDetails|null>(null);const [dispute,setDispute]=useState<DisputeDetails|null>(null);const [links,setLinks]=useState<Record<string,string>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{setData(await request('/marketplace/admin/overview'));}catch(e){setError(e instanceof Error?e.message:'読み込めませんでした');}}
 useEffect(()=>{let active=true;request<{suppliers:Supplier[];services:Service[];disputes:Dispute[]}>('/marketplace/admin/overview').then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'読み込めませんでした');});return()=>{active=false;};},[]);
 async function act(path:string,body:unknown){setBusy(true);setError('');try{await request(path,'POST',body);setSupplier(null);setDispute(null);await load();}catch(e){setError(e instanceof Error?e.message:'保存できませんでした');}finally{setBusy(false);}}
 const values=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
 return <div className="hd-stack"><h1>暮らしの支援・審査と紛争</h1><p>確認書類と作業記録を確認して操作してください。紛争の裁定には二人の運営担当者による承認が必要です。</p>{error&&<p role="alert">{error}</p>}<button className="hd-button" disabled={busy} onClick={()=>void load()}>再読み込み</button>
 <section className="hd-card"><h2>供給者の審査</h2>{data?.suppliers.map(s=><article key={s.id} className="hd-card"><h3>{s.legalName}</h3><p>{statuses[s.reviewStatus]??s.reviewStatus}</p>{isOperator&&s.reviewStatus!=='invited_unverified'&&<button className="hd-button" onClick={()=>void request<SupplierDetails>('/marketplace/admin/suppliers/'+s.id).then(setSupplier).catch(e=>setError(e.message))}>申請・書類を確認</button>}</article>)}</section>
 {supplier&&<section className="hd-card"><h2>{supplier.legalName}の申請内容</h2><p>{supplier.address}</p>{supplier.application?Object.entries(supplier.application).map(([k,v])=><p key={k}><strong>{fieldLabels[k]??'申請内容'}</strong>: {Array.isArray(v)?v.join('、'):v}</p>):<p>必要書類と申請内容が未提出です。</p>}{supplier.evidenceIds.map(id=><p key={id}>{links[id]?<a href={links[id]} target="_blank" rel="noopener noreferrer">確認書類を開く（有効期限あり）</a>:<button className="hd-button" onClick={()=>void request<{url:string}>('/evidence/'+id+'/url').then(r=>setLinks(v=>({...v,[id]:r.url}))).catch(e=>setError(e.message))}>確認書類を表示</button>}</p>)}
 <form className="hd-stack" onSubmit={e=>{const b=values(e);void act('/marketplace/admin/suppliers/'+supplier.id+'/review',b);}}><label>判断<select className="hd-select" name="decision"><option value="rejected">差戻し</option><option value="approved">承認する</option></select></label><label>理由<textarea className="hd-input" name="reason" required maxLength={1000}/></label><button className="hd-button" disabled={busy}>審査結果を保存</button></form></section>}
 <section className="hd-card"><h2>サービスの公開審査</h2>{data?.services.map(s=><article key={s.id} className="hd-card"><h3>{s.name} · {s.supplierName}</h3><p>{s.description}</p><p>{s.pricePolicy}</p><p>{statuses[s.status]??s.status}</p>{isOperator&&<form className="hd-stack" onSubmit={e=>{const b=values(e);void act('/marketplace/services/'+s.id+'/review',b);}}><label>判断<select className="hd-select" name="decision"><option value="paused">休止・差戻し</option><option value="published">公開する</option></select></label><label>審査理由<input className="hd-input" name="reason" required/></label><button className="hd-button" disabled={busy}>保存</button></form>}</article>)}</section>
 <section className="hd-card"><h2>異議申立て</h2>{data?.disputes.length===0&&<p>対応中の異議申立てはありません。</p>}{data?.disputes.map(d=><article key={d.id} className="hd-card"><h3>{d.title}</h3>{isOperator&&<button className="hd-button" onClick={()=>void request<DisputeDetails>('/marketplace/admin/requests/'+d.id+'/dispute').then(setDispute).catch(e=>setError(e.message))}>作業内容・メッセージを確認</button>}{d.reviewId?<><p>提案: {statuses[d.proposedDecision??'']}</p><p>理由: {d.reason}</p><p>確認した記録: {d.evidenceSummary}</p>{isOperator&&<form className="hd-stack" onSubmit={e=>{const b=values(e);void act('/marketplace/admin/requests/'+d.id+'/resolutions/'+d.reviewId+'/approve',{approve:b.approve==='yes',reason:b.reason});}}><label>二次確認<select name="approve" className="hd-select"><option value="no">提案を差戻す</option><option value="yes">裁定を承認する</option></select></label><label>確認理由<textarea className="hd-input" name="reason" required/></label><button className="hd-button" disabled={busy||d.proposedBy===me.id}>{d.proposedBy===me.id?'別の担当者の確認が必要です':'二次確認を保存'}</button></form>}</>:isOperator&&<form className="hd-stack" onSubmit={e=>{void act('/marketplace/admin/requests/'+d.id+'/resolutions',values(e));}}><label>裁定案<select className="hd-select" name="decision"><option value="resolved_cancelled">取消・枠返却</option><option value="resolved_completed">完了・枠消費</option></select></label><label>理由<textarea className="hd-input" name="reason" required/></label><label>確認した作業記録・証拠<textarea className="hd-input" name="evidenceSummary" required minLength={20} maxLength={4000}/></label><button className="hd-button" disabled={busy}>二次確認を依頼</button></form>}</article>)}</section>
 {dispute&&<section className="hd-card"><h2>{dispute.title}の作業記録</h2><p>{dispute.details}</p><p>{dispute.address}</p>{dispute.messages.map((m,i)=><p key={i}>{m.body} · {new Date(m.createdAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</p>)}</section>}
 </div>;
}
