'use client';
import {useEffect,useState} from 'react';
import {appFetch as api} from '@/lib/upload';
type Ticket={id:string;body:string;status:string;answer?:string};type Notice={id:string;title:string;body:string;readAt?:string};
export function CustomerSupport(){const [tickets,setTickets]=useState<Ticket[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [body,setBody]=useState('');const [category,setCategory]=useState('other');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{const [t,n]=await Promise.all([api<Ticket[]>('/support/tickets'),api<Notice[]>('/notifications')]);setTickets(t);setNotices(n);}catch(e){setError(e instanceof Error?e.message:'読み込めませんでした');}}
 useEffect(()=>{let active=true;Promise.all([api<Ticket[]>('/support/tickets'),api<Notice[]>('/notifications')]).then(([t,n])=>{if(active){setTickets(t);setNotices(n);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'読み込めませんでした');});return()=>{active=false;};},[]);
 return <div className="hd-stack">{error&&<p role="alert">{error}</p>}<section className="mp-card"><h2>お知らせ</h2>{notices.length===0&&<p>新しいお知らせはありません。</p>}{notices.map(n=><article key={n.id}><h3>{n.title}</h3><p>{n.body}</p>{!n.readAt&&<button className="mp-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/notifications/read','POST',{ids:[n.id]});await load();}catch(e){setError(e instanceof Error?e.message:'既読にできませんでした');}finally{setBusy(false);}}}>既読にする</button>}</article>)}</section><section className="mp-card"><h2>お問い合わせ</h2><p>依頼に関する問題は、依頼詳細の「サポートに相談」からお知らせください。</p><form className="hd-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/support/tickets','POST',{category,body});setBody('');await load();}catch(e){setError(e instanceof Error?e.message:'送信できませんでした');}finally{setBusy(false);}}}><label>お問い合わせの種類<select aria-label="お問い合わせの種類" className="hd-select" value={category} onChange={e=>setCategory(e.target.value)}>{[['account','アカウント'],['payment','料金・契約'],['safety','安全・事故'],['privacy','個人情報'],['other','その他']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>お問い合わせ内容<textarea className="hd-input" value={body} maxLength={4000} required onChange={e=>setBody(e.target.value)}/></label><button className="mp-button" disabled={busy}>送信する</button></form>{tickets.map(t=><article key={t.id}><p>{t.body}</p><p>{t.status==='closed'?'対応済み':'受付・確認中'}</p>{t.answer&&<p>運営からの回答: {t.answer}</p>}</article>)}</section></div>;
}
