'use client';
import {useEffect,useState} from 'react';
import {marketplaceFetch as api} from '@/lib/marketplace';
import {uploadDocument} from '@/lib/upload';
type Staff={id:string;familyName:string;givenName:string;role:string};
type Invite={id:string;phone:string;role:string;expiresAt:string;acceptedAt:string|null;revokedAt:string|null};
type Schedule={id:string;staffName:string;startsAt:string;endsAt:string};
type Application={reviewStatus:string;reviewReason:string|null;evidenceIds:string[];application:Record<string,string|string[]>|null};
export function SupplierOperations({supplierId,role}:{supplierId:string;role:string}){
 const root='/suppliers/'+supplierId;const manage=role==='owner'||role==='manager';
 const [staff,setStaff]=useState<Staff[]>([]);const [invites,setInvites]=useState<Invite[]>([]);const [schedule,setSchedule]=useState<Schedule[]>([]);const [application,setApplication]=useState<Application|null>(null);
 const [docs,setDocs]=useState<string[]>([]);const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [success,setSuccess]=useState('');
 async function fetchOperations(){const schedules=await api<{items:Schedule[]}>(root+'/availability');if(!manage)return {schedules:schedules.items};const [m,i,a]=await Promise.all([api<{items:Staff[]}>(root+'/members'),api<{items:Invite[]}>(root+'/invitations'),api<Application>(root+'/application')]);return {schedules:schedules.items,staff:m.items,invites:i.items,application:a};}
 function applyOperations(value:Awaited<ReturnType<typeof fetchOperations>>,resetDocs=false){setSchedule(value.schedules);setStaff(value.staff??[]);setInvites(value.invites??[]);setApplication(value.application??null);setDocs(current=>resetDocs?(value.application?.evidenceIds??[]):Array.from(new Set([...current,...(value.application?.evidenceIds??[])])));}
 async function load(){try{applyOperations(await fetchOperations());}catch(e){setError(e instanceof Error?e.message:'読み込めませんでした');}}
 useEffect(()=>{let active=true;fetchOperations().then(value=>{if(active){applyOperations(value,true);setToken('');setError('');}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'読み込めませんでした');});return()=>{active=false;};},[supplierId,role]); // eslint-disable-line react-hooks/exhaustive-deps
 async function act(path:string,b:unknown,method='POST'){if(busy)return;setBusy(true);setError('');setSuccess('');try{const r=await api<{token?:string}>(root+path,method,b);if(r.token)setToken(r.token);setSuccess('保存しました');await load();}catch(e){setError(e instanceof Error?e.message:'保存できませんでした');}finally{setBusy(false);}}
 const values=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget));};
 return <div className="hd-stack">{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
  {manage&&<section className="mp-card"><h2>事業者の申請・審査</h2><p>審査状況: {application?.reviewStatus??'読込中'}</p>{application?.reviewReason&&<p>審査結果: {application.reviewReason}</p>}
  {application&&application.reviewStatus!=='approved'&&<form className="hd-stack" key={application?.reviewStatus} onSubmit={e=>{const b=values(e);if(!b.registrationNumber)delete b.registrationNumber;void act('/application',{...b,areaCodes:String(b.areaCodes).split(',').map(s=>s.trim()).filter(Boolean),evidenceIds:docs},'PUT');}}>
  {[['businessCategory','事業分類'],['registrationNumber','法人番号・登録番号（任意）'],['areaCodes','作業エリアコード（カンマ区切り）'],['openingHours','営業時間'],['insuranceSummary','保険・安全管理'],['contactEmail','連絡先メール'],['description','事業内容・訪問方法']].map(([name,label])=><label key={name}>{label}<input className="hd-input" name={name} required={name!=='registrationNumber'} type={name==='contactEmail'?'email':'text'} defaultValue={Array.isArray(application?.application?.[name!])?(application?.application?.[name!] as string[]).join(','):String(application?.application?.[name!]??'')} /></label>)}
  <label>審査書類の写真（JPEG・PNG）<input type="file" accept="image/jpeg,image/png" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const id=await uploadDocument(file);setDocs(v=>[...v,id]);}catch(error){setError(error instanceof Error?error.message:'書類をアップロードできませんでした');}finally{setBusy(false);}}}/></label><p>登録済みの書類: {docs.length}件</p><button className="mp-button" disabled={busy||!docs.length}>申請を提出</button></form>}
  </section>}
  {manage&&<section className="mp-card"><h2>担当者を招待</h2><p>相手がこの電話番号をSMSで確認してから、招待コードで参加します。</p><form className="hd-stack" onSubmit={e=>{void act('/invitations',values(e));}}><label>招待する電話番号<input className="hd-input" name="phone" type="tel" required/></label><label>権限<select className="hd-select" name="role"><option value="staff">担当者</option>{role==='owner'&&<option value="manager">管理者</option>}</select></label><button className="mp-button" disabled={busy}>招待コードを作成</button></form>{token&&<div><label>招待コード<input className="hd-input" readOnly value={token}/></label><button className="mp-button" onClick={()=>void navigator.clipboard.writeText(token).catch(()=>setError('招待コードを選択してコピーしてください'))}>コピー</button><p>7日以内に、招待した相手へ安全に共有してください。</p></div>}
  {invites.map(i=><p key={i.id}>{i.phone} · {i.acceptedAt?'参加済み':i.revokedAt?'無効':'招待中'} {!i.acceptedAt&&!i.revokedAt&&<button className="mp-button" disabled={busy} onClick={()=>void act('/invitations/'+i.id+'/revoke',{})}>招待を取り消す</button>}</p>)}</section>}
  {manage&&<section className="mp-card"><h2>担当者一覧</h2>{staff.map(s=><p key={s.id}>{s.familyName} {s.givenName} · {s.role} {s.role!=='owner'&&(role==='owner'||s.role==='staff')&&<button className="mp-button" disabled={busy} onClick={()=>{const reason=window.prompt('担当中の依頼がないことを確認して、解除理由を入力してください');if(reason)void act('/members/'+s.id+'/deactivate',{reason});}}>参加を解除</button>}</p>)}</section>}
  <section className="mp-card"><h2>担当者の対応予定</h2>{schedule.length===0&&<p>対応時間は未登録です。</p>}{schedule.map(s=><p key={s.id}>{s.staffName} · {new Date(s.startsAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}〜{new Date(s.endsAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} {manage&&<button className="mp-button" disabled={busy} onClick={()=>void act('/availability/'+s.id+'/remove',{})}>削除</button>}</p>)}
  {manage&&<form className="hd-stack" onSubmit={e=>{const b=values(e);void act('/availability',{staffId:b.staffId,startsAt:new Date(String(b.startsAt)+'+09:00').toISOString(),endsAt:new Date(String(b.endsAt)+'+09:00').toISOString()});}}><label>担当者<select className="hd-select" name="staffId">{staff.map(s=><option key={s.id} value={s.id}>{s.familyName} {s.givenName}</option>)}</select></label><label>開始（日本時間）<input className="hd-input" type="datetime-local" name="startsAt" required/></label><label>終了（日本時間）<input className="hd-input" type="datetime-local" name="endsAt" required/></label><button className="mp-button" disabled={busy||!staff.length}>対応時間を登録</button></form>}</section>
 </div>;
}
